---
title: "Spatial mortality"
subtitle: "Data preparation"
author: "Radek Panczak"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    highlight: pygments
editor_options: 
  chunk_output_type: console
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../docs") })
---

<!-- ----------------------------------------------------- -->

```{r setup, include = FALSE}
set.seed(12345)
options(scipen = 999)
options(max.print = "75")

library(pacman)
p_load(fst, 
       tidyverse, magrittr, janitor, scales, lubridate, 
       kableExtra)

import::from("sjmisc", "frq")
```


```{r setup, include = FALSE}
tidyverse::tidyverse_conflicts()

# library(conflicted)
conflicted::conflict_scout()
```

```{r knit-setup, include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

knitr::opts_chunk$set(cache = FALSE,
                      prompt = FALSE,
                      tidy = FALSE,
                      comment = NA,
                      message = FALSE,
                      warning = FALSE)

knitr::opts_knit$set(width = 75)

mu <- Hmisc::markupSpecs$html
```

<!-- ----------------------------------------------------- -->

# BfS 

## Spatial data 2020

[Generalisierte Gemeindegrenzen: Geodaten](https://www.bfs.admin.ch/bfs/de/home/dienstleistungen/geostat/geodaten-bundesstatistik/administrative-grenzen/generalisierte-gemeindegrenzen.assetdetail.11947559.html)

```{r eval=FALSE}
download.file(url = "https://www.bfs.admin.ch/bfsstatic/dam/assets/11947559/master",
              destfile = "data-raw/BfS/ag-b-00.03-875-gg20.zip",
              method = "curl")

unzip("data-raw/BfS/ag-b-00.03-875-gg20.zip", exdir = "data-raw/BfS/ag-b-00.03-875-gg20")

unlink("data-raw/BfS/ag-b-00.03-875-gg20.zip")
unlink("data-raw/BfS/ag-b-00.03-875-gg20/txt", recursive = TRUE)
unlink("data-raw/BfS/ag-b-00.03-875-gg20/kmz", recursive = TRUE)
unlink("data-raw/BfS/ag-b-00.03-875-gg20/ggg_2020-LV03", recursive = TRUE)
unlink("data-raw/BfS/ag-b-00.03-875-gg20/ggg_2020-LV95/ggg_2020-LV95.gdb", recursive = TRUE)
```

## Spatial data 2021

[Generalisierte Gemeindegrenzen: Geodaten](https://www.bfs.admin.ch/bfs/de/home/dienstleistungen/geostat/geodaten-bundesstatistik/administrative-grenzen/generalisierte-gemeindegrenzen.assetdetail.17964056.html)

```{r eval=FALSE}
download.file(url = "https://www.bfs.admin.ch/bfsstatic/dam/assets/17964056/master",
              destfile = "data-raw/BfS/ag-b-00.03-875-gg21.zip",
              method = "curl")

unzip("data-raw/BfS/ag-b-00.03-875-gg21.zip", exdir = "data-raw/BfS/ag-b-00.03-875-gg21")

unlink("data-raw/BfS/ag-b-00.03-875-gg21.zip")
unlink("data-raw/BfS/ag-b-00.03-875-gg21/txt", recursive = TRUE)
unlink("data-raw/BfS/ag-b-00.03-875-gg21/kmz", recursive = TRUE)
unlink("data-raw/BfS/ag-b-00.03-875-gg21/ggg_2021-LV03", recursive = TRUE)
unlink("data-raw/BfS/ag-b-00.03-875-gg21/ggg_2021-LV95/ggg_2021-LV95.gdb", recursive = TRUE)
```

## Mortality data

```{r eval=FALSE}
# Deaths by institutional units (canton, district, commune), sex, citizenship (category), marital status and age class
# https://www.bfs.admin.ch/bfs/en/home/statistics/population/births-deaths/deaths.assetdetail.17664403.html
# language https://github.com/cjgb/pxR/issues/9

download.file(url = "https://www.bfs.admin.ch/bfsstatic/dam/assets/17664403/master",
              destfile = "data-raw/BfS/px-x-0102020206_102.px",
              method = "curl")

zip("data-raw/BfS/px-x-0102020206_102.px.zip", files = "data-raw/BfS/px-x-0102020206_102.px")

deaths_1969_2020_raw <- pxR::read.px("data-raw/BfS/px-x-0102020206_102.px",
                                     encoding = "latin9") %>% 
  as_tibble() %>% remove_empty(c("rows", "cols")) %>% clean_names()

# write_rds(deaths_1969_2020_raw, "data-raw/BfS/deaths_1969_2020_raw.Rds")
write_fst(deaths_1969_2020_raw, "data-raw/BfS/deaths_1969_2020_raw.fst")

unlink("data-raw/BfS/px-x-0102020206_102.px")
```

```{r eval=FALSE}
deaths_1969_2020 <- read_fst("data-raw/BfS/deaths_1969_2020_raw.fst") %>% 
  as_tibble() %>% 
  mutate(jahr = as.integer(as.character(jahr))) %>% 
  mutate(kanton_bezirk_gemeinde = as.character(kanton_bezirk_gemeinde)) %>% 
  mutate(value = as.integer(value)) %>% 
  filter(altersklasse != "Altersklasse - Total") %>% 
  filter(staatsangehorigkeit_kategorie != "Staatsangehörigkeit - Total") %>% 
  filter(geschlecht != "Geschlecht - Total") %>% 
  filter(zivilstand != "Zivilstand - Total") %>% 
  filter(str_detect(kanton_bezirk_gemeinde, fixed("......"))) %>% 
  mutate(across(where(is.factor), fct_drop))

levels(deaths_1969_2020$zivilstand)

geonames <- deaths_1969_2020 %>% 
  select(kanton_bezirk_gemeinde) %>% 
  distinct() %>% 
  mutate(temp = str_replace(kanton_bezirk_gemeinde, fixed("......"), "")) %>% 
  mutate(gemeinde_num = word(temp, 1, 1) ,
         gemeinde_txt = word(temp, 2, -1)) %>% 
  select(-temp)

deaths_1969_2020 %<>%
  left_join(geonames) %>% 
  relocate(gemeinde_num, gemeinde_txt) %>% 
  select(-kanton_bezirk_gemeinde) %>% 
  rename(
    year = jahr, 
    nationality = staatsangehorigkeit_kategorie,
    age = altersklasse,
    civil = zivilstand,
    sex = geschlecht
  ) 

deaths_1969_2020 %<>%
  mutate(
    sex =         fct_recode(sex, 
                             Men   = "Mann", 
                             Women = "Frau"),
    civil =       fct_recode(civil, 
                             Single      = "Ledig",
                             Verheiratet = "Married", 
                             Verwitwet   = "Widowed", 
                             Geschieden  = "Divorced", 
                             Anderer     = "Other"),
    nationality = fct_recode(nationality, 
                             Swiss     = "Schweiz", 
                             Foreigner = "Ausland"),
    age =         fct_recode(age, 
                             "<20" = "Unter 20 Jahren", 
                             "20-29" = "20-29 Jahre", 
                             "30-39" = "30-39 Jahre", 
                             "40-49" = "40-49 Jahre", 
                             "50-59" = "50-59 Jahre", 
                             "60-69" = "60-69 Jahre", 
                             "70-79" = "70-79 Jahre", 
                             "80-89" = "80-89 Jahre", 
                             ">90" = "90 Jahre und mehr")
  )
# ) %>% 
# mutate(civil = fct_relevel(civil, "Married"))

levels(deaths_1969_2020$civil) # and why on earth only single works?

levels(deaths_1969_2020$civil) <- c( 
                             Single      = "Ledig",
                             Verheiratet = "Married", 
                             Verwitwet   = "Widowed", 
                             Geschieden  = "Divorced", 
                             Anderer     = "Other")

levels(deaths_1969_2020$civil) # now it's all flipped?

write_fst(deaths_1969_2020, "data/BfS/deaths_1969_2020.fst")
rm(geonames); gc()
```

```{r}
deaths_2015_2020 <- read_fst("data/BfS/deaths_1969_2020.fst") %>% 
  as_tibble() %>% 
  filter(year >= 2015)
```

