---
title: "Spatial analyses of 2020-21 excess mortality in CH"
subtitle: "Ancillary data preparation"
author: "Radek Panczak"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    highlight: pygments
editor_options: 
  chunk_output_type: console
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../docs") })
---

<!-- ----------------------------------------------------- -->

```{r setup, include = FALSE}
set.seed(12345)
options(scipen = 999)
options(max.print = "75")

library(pacman)
p_load(fst, readxl, 
       tidyverse, magrittr, janitor, scales, lubridate, kableExtra,
       sf, tmap)

import::from("sjmisc", "frq")
```


```{r conflicts, include = FALSE}
tidyverse::tidyverse_conflicts()

conflicted::conflict_scout()
```

```{r knit-setup, include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

knitr::opts_chunk$set(cache = FALSE,
                      prompt = FALSE,
                      tidy = FALSE,
                      comment = NA,
                      message = FALSE,
                      warning = FALSE)

knitr::opts_knit$set(width = 75)

mu <- Hmisc::markupSpecs$html
```

<!-- ----------------------------------------------------- -->

```{r include=FALSE}
# prepared in 01.Rmd
gg21 <- read_rds("data/BfS/gg21.Rds")
se21 <- read_rds("data/BfS/se21.Rds")
kt21 <- read_rds("data/BfS/kt21.Rds")

st_gg21 <- read_rds("data/swisstopo/st_gg21.Rds")
```

# Population

px-x-0102010000_103.xlsx


# Cartogram


# Swiss-SEP


# Raumgliederungen 

From the [app](https://www.agvchapp.bfs.admin.ch/de/typologies/query). State as of `2021-07-01` to match spatial data nicely.  

```{r}
raum <- read_xlsx("data-raw/BfS/Raumgliederungen.xlsx", 
                  skip = 1) %>% 
  remove_empty(c("rows", "cols")) %>% clean_names() %>% 
  filter(! is.na(bfs_gde_nummer)) %>% 
  rename(GMDNR = bfs_gde_nummer,
         GMDNAME = gemeindename,
         KTNAME = kanton,
         BZNR = bezirks_nummer,
         BZNAME = bezirksname) %>% 
  select(GMDNR, GMDNAME, KTNAME, BZNR, BZNAME, 
         stadtische_landliche_gebiete, sprachgebiete,
         urbanisierungsgrad_2011_degurba_eurostat) %>% 
  mutate(
    r_urban1 = case_when(
      stadtische_landliche_gebiete == 1 ~  "Urban",
      stadtische_landliche_gebiete == 2 ~  "Periurban",
      stadtische_landliche_gebiete == 3 ~  "Rural",
      TRUE ~  ""),
     r_urban2 = case_when(
      urbanisierungsgrad_2011_degurba_eurostat == 1 ~  "Dense",
      urbanisierungsgrad_2011_degurba_eurostat == 2 ~  "Medium",
      urbanisierungsgrad_2011_degurba_eurostat == 3 ~  "Low",
      TRUE ~  ""),
    r_lang = case_when(
      sprachgebiete == 1 ~  "German",
      sprachgebiete == 2 ~  "French",
      sprachgebiete == 3 ~  "Italian",
      sprachgebiete == 4 ~  "Romansh",
      TRUE ~  "")
  ) %>% 
  select(-stadtische_landliche_gebiete, -sprachgebiete,
         -urbanisierungsgrad_2011_degurba_eurostat)
```

```{r include=FALSE}
stopifnot(nrow(anti_join(raum, gg21)) == 0)

gg21_merged <- gg21 %>% 
  left_join(raum) %>% 
  relocate(KTNAME, .after = KTNR)
```

## Urbanization 1 

```{r echo=FALSE}
frq(raum, r_urban1)

tm_shape(se21, is.master = FALSE) +
  tm_fill(col = "#a7cdf2")  +
  tm_shape(gg21_merged) +
  tm_fill(col = "r_urban1")  +
  tm_shape(kt21) +
  tm_borders()  +
  tm_layout(
    title = "Urbanization 2021"
  )
```

## Urbanization 2 

Using [DEGURBA](https://ec.europa.eu/eurostat/web/degree-of-urbanisation/background).  
```{r echo=FALSE}
frq(raum, r_urban2)

tm_shape(se21, is.master = FALSE) +
  tm_fill(col = "#a7cdf2")  +
  tm_shape(gg21_merged) +
  tm_fill(col = "r_urban2")  +
  tm_shape(kt21) +
  tm_borders()  +
  tm_layout(
    title = "Urbanization 2021"
  )
```

## Language region

```{r echo=FALSE}
frq(raum, r_lang)

tm_shape(se21, is.master = FALSE) +
  tm_fill(col = "#a7cdf2")  +
  tm_shape(gg21_merged) +
  tm_fill(col = "r_lang")  +
  tm_shape(kt21) +
  tm_borders()  +
  tm_layout(
    title = "Language region 2021"
  )
```
