---
title: "Spatial analyses of 2020-21 excess mortality in CH"
subtitle: "Grid & grided data preparation"
author: "Radek Panczak & Garyfallos Konstantinoudis"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    highlight: pygments
editor_options: 
  chunk_output_type: console
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../docs") })
---

<!-- ----------------------------------------------------- -->

```{r setup, include = FALSE}
set.seed(12345)
options(scipen = 999)
options(max.print = "75")

library(pacman)
p_load(tidyverse, magrittr, scales,  
       DT, 
       sf, tmap)

import::from("sjmisc", "frq")
```


```{r conflicts, include = FALSE}
tidyverse::tidyverse_conflicts()

conflicted::conflict_scout()
```

```{r knit-setup, include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

knitr::opts_chunk$set(cache = FALSE,
                      prompt = FALSE,
                      tidy = FALSE,
                      comment = NA,
                      message = FALSE,
                      warning = FALSE)

knitr::opts_knit$set(width = 75)

mu <- Hmisc::markupSpecs$html
```

<!-- ----------------------------------------------------- -->

# Geo 

```{r}
gg21 <- read_rds("data/BfS/gg21.Rds")

st_gg21 <- read_rds("data/swisstopo/st_gg21.Rds")
```

<!-- ----------------------------------------------------- -->

# STATPOP

Could be used to define `offset` for `st_make_grid`

```{r}
statpop_20 <- read_delim("data-raw/BfS/ag-b-00.03-vz2020statpop/STATPOP2020.zip", 
                         delim = ";", escape_double = FALSE, trim_ws = TRUE)[] %>% 
  mutate_all(as.integer)

offset <- statpop_20 %>% 
  summarise(minX = min(E_KOORD),
            minY = min(N_KOORD))

# statpop_20 %>% slice(1:10) %>% View()
```

<!-- ----------------------------------------------------- -->

# Grid

```{r eval=FALSE, include=FALSE}
grid_100m <- st_gg21 %>% 
  st_make_grid(cellsize = 100, square = TRUE, 
               offset = c(offset$minX, offset$minY)) %>% 
  st_intersection(st_gg21)  %>%
  st_sf() %>%
  st_cast() %>% 
  mutate(ID = row_number(),
         area = st_area(.)) %>% 
  relocate(ID, area)
```

1-km grid, with lower left corner defined using `STATPOP` cells and clippet using swisstopo municipality data.  

Adding ID for each cell (based on row number).  

```{r}
grid_1km <- st_gg21 %>% 
  st_make_grid(cellsize = 1000, square = TRUE, 
               offset = c(offset$minX, offset$minY)) %>% 
  st_sf() %>%
  st_cast()
```


```{r}
grid_1km_crop <- grid_1km %>% 
  st_intersection(st_gg21)  %>%
  mutate(ID = row_number(),
         area = st_area(.)) %>% 
  relocate(ID, area)
```

```{r}
plot(st_geometry(grid_1km_crop))
```

