---
title: "Spatial analyses of 2020-21 excess mortality in CH"
subtitle: "EDA"
author: "Radek Panczak"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    highlight: pygments
editor_options: 
  chunk_output_type: console
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../docs") })
---

<!-- ----------------------------------------------------- -->

```{r setup, include = FALSE}
set.seed(12345)
options(scipen = 999)
options(max.print = "75")

library(pacman)
p_load(sf, tidyverse, magrittr, scales, DT, tmap)

import::from("sjmisc", "frq")
```

```{r conflicts, include = FALSE}
tidyverse::tidyverse_conflicts()

conflicted::conflict_scout()
```

```{r knit-setup, include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

knitr::opts_chunk$set(cache = FALSE,
                      prompt = FALSE,
                      tidy = FALSE,
                      comment = NA,
                      message = FALSE,
                      warning = FALSE)

knitr::opts_knit$set(width = 75)

mu <- Hmisc::markupSpecs$html
```

<!-- ----------------------------------------------------- -->

# Deaths > population

## AR level

```{r}
w_deaths_2015_2021_ar_pop <- read_rds("data/BfS-closed/w_deaths_2015_2021_ar_pop.Rds")
```

```{r}
w_deaths_2015_2021_ar_pop %>%
  group_by(year) %>%
  summarise(deaths = sum(deaths))

length(unique(w_deaths_2015_2021_ar_pop$ARNR))
```

```{r}
frq(w_deaths_2015_2021_ar_pop, deaths > population)
```

```{r}
w_deaths_2015_2021_ar_pop %>% 
  filter(deaths > population) %>% 
  mutate(diff = deaths - population) %>% 
  select(diff) %>% 
  summary()
```

```{r}
w_deaths_2015_2021_ar_pop %>% 
  mutate(diff = population - deaths) %>% 
  filter(deaths > population) %>% 
  datatable()
```

## Municipality level 

```{r}
w_deaths_2015_2021_pop <- read_rds("data/BfS-closed/w_deaths_2015_2021_pop.Rds")
```

```{r}
length(unique(w_deaths_2015_2021_pop$GMDNR))
```

```{r eval=FALSE, include=FALSE}
frq(w_deaths_2015_2021_pop, deaths > population)
```

```{r eval=FALSE, include=FALSE}
w_deaths_2015_2021_pop %>% 
  filter(deaths > population) %>% 
  mutate(diff = deaths - population) %>% 
  select(diff) %>% 
  summary()
```

```{r eval=FALSE, include=FALSE}
w_deaths_2015_2021_pop %>% 
  mutate(diff = population - deaths) %>% 
  filter(deaths > population) %>% 
  datatable()
```

```{r}
frq(w_deaths_2015_2021_pop, deaths > population_mid_poi)
```

```{r}
w_deaths_2015_2021_pop %>% 
  filter(deaths > population_mid_poi) %>% 
  mutate(diff = deaths - population_mid_poi) %>% 
  select(diff) %>% 
  summary()
```

```{r}
w_deaths_2015_2021_pop %>% 
  mutate(diff = population_mid_poi - deaths) %>% 
  filter(deaths > population_mid_poi) %>% 
  datatable()
```

<!-- ----------------------------------------------------- -->

# Differences in pop estimates (municipality)

## Age group specific diffs

```{r}
frq(w_deaths_2015_2021_pop, population_mid_lm > population) 

pop_diff <- w_deaths_2015_2021_pop %>% 
  mutate(pop_diff = population_mid_lm - population,
         perc_diff = (pop_diff / population_mid_lm) * 100)

summary(pop_diff$pop_diff)
summary(pop_diff$perc_diff)
```

## Municipality specific diffs

```{r}
gg21 <- readRDS("data/BfS/gg21.Rds")

gg21_centr <- st_centroid(gg21)

pop_diff <- w_deaths_2015_2021_pop %>% 
  group_by(GMDNR) %>% 
  summarise(deaths = sum(deaths),
            population = sum(population),
            population_mid_poi = sum(population_mid_poi)) %>% 
  ungroup() %>% 
  mutate(pop_diff = population_mid_poi - population,
         perc_diff = (pop_diff / population_mid_poi) * 100)

summary(pop_diff$pop_diff)
summary(pop_diff$perc_diff)

gg21 %<>% 
  left_join(pop_diff)

gg21_centr %<>% 
  left_join(pop_diff)
```

```{r}
gg21 %>% 
  st_drop_geometry() %>% 
  ggplot() +
  geom_histogram(aes(pop_diff))
```

```{r}
gg21 %>% 
  st_drop_geometry() %>% 
  ggplot() +
  geom_histogram(aes(perc_diff))
```

```{r}
gg21 %>% 
  st_drop_geometry() %>% 
  ggplot() +
  geom_point(aes(pop_diff, perc_diff))
```

```{r}
tmap_mode("view")

tm_shape(gg21_centr) +
  tm_bubbles(size = "population_mid_poi", col = "perc_diff",
             style = "fixed", breaks = c(-5, -3, -1, 0, 1, 3, 5.5))
```