---
title: "Spatial analyses of 2020-21 excess mortality in CH"
subtitle: "Analyses using AR"
author: "Radek Panczak"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    highlight: pygments
editor_options: 
  chunk_output_type: console
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../docs") })
---

<!-- ----------------------------------------------------- -->

```{r setup, include = FALSE}
set.seed(12345)
options(scipen = 999)
options(max.print = "75")

library(pacman)
p_load(tidyverse, magrittr, scales,  
       sf, tmap,
       INLA)

import::from("sjmisc", "frq")
```

```{r conflicts, include = FALSE}
tidyverse::tidyverse_conflicts()

conflicted::conflict_scout()
```

```{r knit-setup, include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

knitr::opts_chunk$set(cache = FALSE,
                      prompt = FALSE,
                      tidy = FALSE,
                      comment = NA,
                      message = FALSE,
                      warning = FALSE)

knitr::opts_knit$set(width = 75)

mu <- Hmisc::markupSpecs$html
```

<!-- ----------------------------------------------------- -->

# Data 

## Deaths

```{r}
w_deaths_2015_2021_ar_pop <- read_rds("data/BfS-closed/w_deaths_2015_2021_ar_pop.Rds") %>% 
  mutate(id_time = as.numeric(as.factor(date))) %>% 
  # select(-date) %>% 
  relocate(id_time, .after = month) %>% 
  mutate(id_space = as.integer(as.factor(ARNR))) %>% 
  relocate(id_space, .after = id_time)
```

## Spatial 

```{r}
ar21 <- readRDS("data/BfS/ar21.Rds")
# argr21 <- readRDS("data/BfS/argr21.Rds")
tg3o_ar <- readRDS("data/geo/tg3o_ar.Rds")
```

<!-- ----------------------------------------------------- -->

# Time series plots

## Aggregated data 

```{r}
data <- w_deaths_2015_2021_ar_pop %>% 
  mutate(rate = 1000 * deaths / population) %>% 
  group_by(ARNAME, date) %>% 
  summarize(deaths = sum(deaths),
            CDR = weighted.mean(rate, population)) %>% 
  ungroup() 
```

## Deaths

```{r echo=FALSE}
ggplot(data, aes(x = date, y = deaths, group = ARNAME)) + 
  geom_line(colour = "darkorchid", alpha = 0.25) +
  theme_minimal() + 
  ylab("Number of deaths") + xlab("")
```

## Crude mort rates

```{r echo=FALSE}
ggplot(data, aes(x = date, y = CDR, group = ARNAME)) + 
  geom_line(colour = "darkorchid", alpha = 0.25) +
  theme_minimal() + 
  ylab("Crude death rate [per 10,000]") + xlab("")
```

<!-- ----------------------------------------------------- -->

# Tiles 

## All

```{r echo=FALSE}
ggplot(data, aes(x = date, y = ARNAME, fill = CDR)) + 
  geom_tile(color = "white", size = 0.05) +
  coord_equal(ratio = 50) + 
  scale_fill_viridis_c(option = "E", direction = -1) + 
  theme_minimal() + 
  ylab("") + xlab("")
```

## Selected 

```{r echo=FALSE}
scales <- data %>% 
  filter(ARNAME %in% c("Biasca", "Bern")) %>% 
  summarise(min = min(CDR),
            max = max(CDR))

p1 <- data %>% 
  filter(ARNAME %in% c("Biasca")) %>% 
  ggplot(aes(x = date, y = "Biasca", fill = CDR)) + 
  geom_tile(color = "white", size = 0.05) +
  coord_equal(ratio = 50) + 
  scale_fill_viridis_c(limits = c(scales$min, scales$max),
                       option = "E", direction = -1) + 
  facet_grid(rows = vars(ARNAME)) +
  theme_minimal() + 
  theme(axis.title.y = element_blank(),
        axis.ticks.y = element_blank(),
        strip.background = element_blank(),
        strip.text.y = element_blank()) +
  ylab("") + xlab("")

p2 <- data %>% 
  filter(ARNAME %in% c("Bern")) %>% 
  ggplot(aes(x = date, y = "Bern", fill = CDR)) + 
  geom_tile(color = "white", size = 0.05) +
  coord_equal(ratio = 50) + 
  scale_fill_viridis_c(limits = c(scales$min, scales$max),
                       option = "E", direction = -1) + 
  facet_grid(rows = vars(ARNAME)) +
  theme_minimal() + 
  theme(axis.title.y = element_blank(),
        axis.ticks.y = element_blank(),
        strip.background = element_blank(),
        strip.text.y = element_blank()) +
  ylab("") + xlab("")

ggpubr::ggarrange(
  p1, p2,
  ncol = 1,
  common.legend = TRUE, legend = "bottom"
)
```

<!-- ----------------------------------------------------- -->

# Simple modelling

## Data

```{r}
model_data <- w_deaths_2015_2021_ar_pop %>% 
  select(-ARGRNR, -ARGRNAME, -KTNAME) %>% 
  mutate(id_year = year - 2014,
         observed = deaths) %>% 
  relocate(observed, .before = deaths) %>% 
  relocate(id_year, .before = year) %>% 
  mutate(deaths = if_else(year >= 2020, NA_integer_, observed)) %>% 
  filter(age == "80+" & sex == "Female") %>% 
  select(-age, - sex)

# sapply(model_data, function(x) sum(is.na(x)))
```

## INLA setup

```{r}
# priors
hyper.iid <- list(theta = list(prior = "pc.prec", param = c(1, 0.01)))
hyper.bym <- list(theta1 = list("PCprior", c(1, 0.01)), 
                  theta2 = list("PCprior", c(0.5, 0.5)))

# Under Poisson uses default set up
control.family <- inla.set.control.family.default()
```

## iid space

```{r}
f1 <-
  deaths ~ 1 + offset(log(population)) + 
  f(id_time, model = "rw2", hyper = hyper.iid, constr = TRUE, scale.model = TRUE) +
  f(id_year, model = "iid", hyper = hyper.iid, constr = TRUE) +
  f(month, model = "rw1", hyper = hyper.iid, constr = TRUE, scale.model = TRUE, cyclic = TRUE)  +
  f(id_space, model = "iid", hyper = hyper.iid, constr = TRUE)

m1 <- inla(f1,
           data = model_data,
           family = "Poisson",
           # verbose = TRUE,
           control.family = control.family,
           control.compute = list(config = TRUE, 
                                  return.marginals.predictor = TRUE,
                                  # cpo = TRUE,
                                  dic = TRUE, waic = TRUE),
           control.mode = list(restart = TRUE),
           num.threads = round(parallel::detectCores() * .8),
           control.predictor = list(compute = TRUE, 
                                    link = 1)
           # , control.inla = list(int.strategy = "grid", diff.logdens = 4)
           # , control.inla = list(strategy = "laplace", npoints = 21)
)

summary(m1)
m1$summary.hyperpar

m1_time <- m1$summary.random$id_time %>% 
  mutate(`0.025quant` = exp(`0.025quant`),
         `0.5quant` = exp(`0.5quant`),
         `0.975quant` = exp(`0.975quant`))

m1_time %>% 
  filter(ID <= 60) %>%
  ggplot(aes(x = ID)) + 
  geom_ribbon(aes(ymin = `0.025quant`, ymax = `0.975quant`), alpha = 0.1) + 
  geom_line(aes(y = `0.5quant`)) + 
  theme_minimal()

m1_month <- m1$summary.random$month %>% 
  mutate(`0.025quant` = exp(`0.025quant`),
         `0.5quant` = exp(`0.5quant`),
         `0.975quant` = exp(`0.975quant`))

m1_month %>% 
  ggplot(aes(x = ID)) + 
  geom_ribbon(aes(ymin = `0.025quant`, ymax = `0.975quant`), alpha = 0.1) + 
  geom_line(aes(y = `0.5quant`)) + 
  theme_minimal()

m1_year <- m1$summary.random$id_year %>% 
  mutate(ID = ID + 2014, 
         `0.025quant` = exp(`0.025quant`),
         `0.5quant` = exp(`0.5quant`),
         `0.975quant` = exp(`0.975quant`))

m1_year %>% 
  ggplot(aes(x = ID)) + 
  geom_ribbon(aes(ymin = `0.025quant`, ymax = `0.975quant`), alpha = 0.1) + 
  geom_line(aes(y = `0.5quant`)) + 
  theme_minimal()

m1_fit <- bind_cols(
  model_data,
  m1$summary.fitted.values
) %>% 
  mutate(split = ifelse(id_time <= 60, "Pre", "Pand"))

ggplot(m1_fit) + 
  geom_point(aes(x = `0.5quant`, y = observed), alpha = 0.22) + 
  facet_wrap(vars(split)) +
  theme_minimal()

m1_fit %>% 
  filter(ARNAME == "Bern") %>% 
  ggplot(aes(x = date)) + 
  # geom_ribbon(aes(ymin = `0.025quant`, ymax = `0.975quant`), alpha = 0.1) +
  geom_line(aes(y = `0.5quant`)) + 
  geom_point(aes(y = observed), alpha = 0.22) + 
  # facet_wrap(vars(split), scales = "free_x") +
  theme_minimal()

m1_space <- 
  ar21 %>%
  # tg3o_ar %>%
  left_join(model_data %>% select(ARNR, id_space) %>% distinct()) %>% 
  left_join(m1$summary.random$id_space %>% 
              mutate(`0.025quant` = exp(`0.025quant`),
                     `0.5quant` = exp(`0.5quant`),
                     `0.975quant` = exp(`0.975quant`)), 
            by = c("id_space" = "ID")) %>% 
  mutate(`0.5quant` = exp(`0.5quant`))

tm_shape(m1_space) + 
  tm_fill("0.5quant")
```

```{r eval=FALSE, include=FALSE}
list_marginals <- m1$marginals.fitted.values

marginals <- data.frame(do.call(rbind, list_marginals))
marginals$ID <- rep(names(list_marginals),
                           times = sapply(list_marginals, nrow))
```

```{r eval=FALSE, include=FALSE}
improved_m1 = inla.cpo(m1)

m1_fit <- bind_cols(
  model_data,
  improved_m1$summary.fitted.values
) %>% 
  mutate(split = ifelse(id_time <= 60, "Pre", "Pand"))

ggplot(m1_fit) + 
  geom_point(aes(x = `0.5quant`, y = observed), alpha = 0.22) + 
  facet_wrap(vars(split)) +
  theme_minimal()

m1_fit %>% 
  filter(ARNAME == "Bern") %>% 
  ggplot(aes(x = date)) + 
  # geom_ribbon(aes(ymin = `0.025quant`, ymax = `0.975quant`), alpha = 0.1) +
  geom_line(aes(y = `0.5quant`)) + 
  geom_point(aes(y = observed), alpha = 0.22) + 
  theme_minimal()
```

## Spatial version

```{r}
f2 <-
  deaths ~ 1 + offset(log(population)) + 
  f(id_time, model = "rw2", hyper = hyper.iid, constr = TRUE, scale.model = TRUE) +
  f(id_year, model = "iid", hyper = hyper.iid, constr = TRUE) +
  f(month, model = "rw1", hyper = hyper.iid, constr = TRUE, scale.model = TRUE, cyclic = TRUE)  +
  f(id_space, model = "bym2", graph = "data/nb/ar21_wm_q.adj", scale.model = TRUE, constr = TRUE, hyper = hyper.bym)

m2 <- inla(f2,
           data = model_data,
           family = "Poisson",
           # verbose = TRUE,
           control.family = control.family,
           control.compute = list(config = TRUE, 
                                  return.marginals.predictor = TRUE,
                                  # cpo = TRUE,
                                  dic = TRUE, waic = TRUE),
           control.mode = list(restart = TRUE),
           num.threads = round(parallel::detectCores() * .8),
           control.predictor = list(compute = TRUE, link = 1)
           # , control.inla = list(int.strategy = "grid", diff.logdens = 4)
           # , control.inla = list(strategy = "laplace", npoints = 21)
)

summary(m2)
m2$summary.hyperpar

m2_time <- m2$summary.random$id_time %>% 
  mutate(`0.025quant` = exp(`0.025quant`),
         `0.5quant` = exp(`0.5quant`),
         `0.975quant` = exp(`0.975quant`))

m2_time %>% 
  filter(ID <= 60) %>%
  ggplot(aes(x = ID)) + 
  geom_ribbon(aes(ymin = `0.025quant`, ymax = `0.975quant`), alpha = 0.1) + 
  geom_line(aes(y = `0.5quant`)) + 
  theme_minimal()

m2_month <- m2$summary.random$month %>% 
  mutate(`0.025quant` = exp(`0.025quant`),
         `0.5quant` = exp(`0.5quant`),
         `0.975quant` = exp(`0.975quant`))

m2_month %>% 
  ggplot(aes(x = ID)) + 
  geom_ribbon(aes(ymin = `0.025quant`, ymax = `0.975quant`), alpha = 0.1) + 
  geom_line(aes(y = `0.5quant`)) + 
  theme_minimal()

m2_year <- m2$summary.random$id_year %>% 
  mutate(ID = ID + 2014, 
         `0.025quant` = exp(`0.025quant`),
         `0.5quant` = exp(`0.5quant`),
         `0.975quant` = exp(`0.975quant`))

m2_year %>% 
  ggplot(aes(x = ID)) + 
  geom_ribbon(aes(ymin = `0.025quant`, ymax = `0.975quant`), alpha = 0.1) + 
  geom_line(aes(y = `0.5quant`)) + 
  theme_minimal()

m2_fit <- bind_cols(
  model_data,
  m2$summary.fitted.values
) %>% 
  mutate(split = ifelse(id_time <= 60, "Pre", "Pand"))

ggplot(m2_fit) + 
  geom_point(aes(x = `0.5quant`, y = observed), alpha = 0.22) + 
  facet_wrap(vars(split)) +
  theme_minimal()

m2_fit %>% 
  filter(ARNAME == "Lugano") %>% 
  ggplot(aes(x = date)) + 
  # geom_ribbon(aes(ymin = `0.025quant`, ymax = `0.975quant`), alpha = 0.1) +
  geom_line(aes(y = `0.5quant`)) + 
  geom_point(aes(y = observed), alpha = 0.22) + 
  # facet_wrap(vars(split), scales = "free_x") +
  theme_minimal()

m2_space <-
  # ar21 %>%
  tg3o_ar %>%
  left_join(model_data %>% select(ARNR, id_space) %>% distinct()) %>%
  left_join(m2$summary.random$id_space %>%
              slice(1:nrow(ar21)) %>% 
              mutate(`0.025quant` = exp(`0.025quant`),
                     `0.5quant` = exp(`0.5quant`),
                     `0.975quant` = exp(`0.975quant`)),
            by = c("id_space" = "ID")) %>%
  mutate(`0.5quant` = exp(`0.5quant`))

tm_shape(m2_space) +
  tm_fill("0.5quant")
```

## Compare 

```{r}
marg.variance <- inla.tmarginal(function(x) 1/x,
                                m1$marginals.hyperpar$"Precision for id_space")
inla.zmarginal(marg.variance)


marg.variance <- inla.tmarginal(function(x) 1/x,
                                m2$marginals.hyperpar$"Precision for id_space")
inla.zmarginal(marg.variance)

rm(marg.variance, m, mm); gc()

dotchart(
  c(
    m1$dic$dic,
    m2$dic$dic
  ), labels = c(
    "m1", "m2"
  )
)

dotchart(
  c(
    m1$waic$waic,
    m2$waic$waic
  ), labels = c(
    "m1", "m2"
  )
)

m1$cpo$cpo
m1$cpo$pit

m2$cpo$cpo
m2$cpo$pit
```

